version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strava-next
      POSTGRES_USER: strava-next
      POSTGRES_PASSWORD: bigandyiscool
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
